# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0002_auto_20180305_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Glasgow', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='geo_data',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='post_code',
            field=models.CharField(default='G3 8PY', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
