# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0002_auto_20180227_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested', to='whats_on_dot_com.UserProfile'),
        ),
    ]
