# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0003_auto_20180322_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, upload_to=b'event_images/'),
        ),
    ]
