# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0003_auto_20180306_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geo_data',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
