# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0004_auto_20180306_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='post_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=512),
        ),
    ]
