# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0005_merge_20180306_1742'),
        ('whats_on_dot_com', '0002_auto_20180306_1011'),
    ]

    operations = [
    ]
