# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0005_auto_20180325_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='whats_on_dot_com.UserProfile'),
        ),
    ]
