# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0006_auto_20180320_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='whats_on_dot_com.Category'),
        ),
    ]
