# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0006_auto_20180327_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
    ]
