# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0007_auto_20180312_2125'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
