# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_on_dot_com', '0007_auto_20180327_1935'),
        ('whats_on_dot_com', '0004_auto_20180327_1534'),
    ]

    operations = [
    ]
